version: "3.10"
services:
  app:
    build: ./app
    working_dir: /app/
    restart: always
    depends_on:
      - ch
    links:
      - ch
    volumes:
      - ./app:/app
    entrypoint:
      - python
      - main.py
    environment:
      - TZ=Europe/Moscow

  ch:
    image: yandex/clickhouse-server
    volumes:
      - ../chdb/db:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    expose:
      - 8123
      - 9000
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144