version: "3.9"
services:
  ch:
    image: yandex/clickhouse-server
    volumes:
      - ./db:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    expose:
      - 8123
      - 9000
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
